name: Build and release the Make docker project

pool:
  vmImage: "ubuntu-latest"

trigger:
  branches:
    include:
      - "*"

stages:
  - stage: Building
    jobs:
      - job: Docker_build
        steps:
          - script: |
              make docker-build
            displayName: Docker build
            env:
              GITHUB_REF: $(Build.SourceBranch)

  - stage: Deploy
    jobs:
      - job: Deploy_Container
        variables:
          - group: make-docker-project
        condition: and(succeeded(), or( eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceVersionMessage'], 'deploy')))
        steps:
          - script: |
              make docker-login
            displayName: "Login to AWS"
            env:
              AWS_ACCESS_KEY_ID: $(ecr-aws-key)
              AWS_SECRET_ACCESS_KEY: $(ecr-aws-secret)
              AWS_REGION: $(ecr-aws-region)
          - script: |
              make docker-build
            displayName: Docker build
            env:
              GITHUB_REF: $(Build.SourceBranch)
          - script: |
              make docker-push
            displayName: Docker push
            env:
              GITHUB_REF: $(Build.SourceBranch)
         
         
